blank_issues_enabled: false
contact_links:
  - name: Join our Official Discord
    about: Join the Pixel Stories Discord server to get help and support from the community.
    url: https://discord.gg/WTxUC4hEnS
